import = [
    "~/.config/alacritty/themes/themes/monokai_pro.toml"
]
# Window settings
[window]
    padding.x=5
    padding.y=5
decorations="Full"
opacity=1
# Font settings
[font]
size=13.0
normal={ family = "MesloLGSDZNerdFont", style = "Regular"}
# Cursor settings
[cursor]
  style= "Block"
[scrolling]
history = 100000
[selection]
save_to_clipboard = true

[keyboard]
bindings = [
        { key="Insert", mods="Shift", action="Paste" },
        { key="Insert", mods="Control", action="Copy" },
        { key= "=", mods= "Control", action= "IncreaseFontSize" },
        { key= "-", mods= "Control", action= "DecreaseFontSize" },
        { key= "0", mods= "Control", action= "ResetFontSize" },
        { key="F11", action="ToggleFullscreen"}
]
